### ISSUE TITLE
window is not defined when compiling page in NextJS

### ISSUE THREAD

**Issue by Vexcited** [Jungwoo-An/react-editor-js#119] opened 2021-05-15 15:02 UTC
### Environment

- @editorjs/editorjs version: 2.17.0
- react-editor-js version: 1.9.0

### Describe

Hi,
I want to create an editor in my NextJS app and there's the code:
```js
import EditorJs from 'react-editor-js';
import initialData from '../../components/Editor/data.json';

export default function EditorPage () {
    return (
        <EditorJs data={initialData} />
    );
}
```
and I get this error:
![image](https://user-images.githubusercontent.com/59152884/118365874-c1740b00-b59e-11eb-9fed-236b9b1ee46e.png)

I wanted to test out this library by using the basic example but seems it don't work.
Maybe there's not an integration with Next ?

(By the way, sorry for my bad english, I'm french...)
Thanks you !

**Comment by Jungwoo-An** [comment] 2021-05-22 18:12
Duplicate of #58 (Temporary solution exist on that link)

**Closed** 2021-05-22 18:12 UTC
Labels: bug
