### ISSUE TITLE
Inline style doesnt show correctly

### ISSUE THREAD

**Issue by danilockthar** [Jungwoo-An/react-editor-js#112] opened 2021-04-19 20:37 UTC
Environment
"@editorjs/editorjs": "^2.20.1",

**Comment by Jungwoo-An** [comment] 2021-04-24 06:27
@danilockthar Hi! First of all, thanks for your interest! 👋 

Duplicate of #109 

Thanks!

**Closed by Jungwoo-An** 2021-04-24 06:27 UTC
Labels: bug
